{{- if .Values.enabledAzureKeyVault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "myk8schart.secretProviderName" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                                                # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.azureKeyVault.userAssignedManagedIdentity | quote }}     # Set the clientID of the user-assigned managed identity to use
    tenantId: {{ .Values.azureKeyVault.tenantId | quote }}                                      # The tenant ID of the key vault
    keyvaultName: {{ .Values.azureKeyVault.name | quote }}                                      # Set to the name of your key vault
    cloudName: ""                                                                               # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        {{- range .Values.azureKeyVault.secrets }}
        - |
          objectName: {{ .name }}
          objectAlias: {{ .alias }}
          objectType: secret
        {{- end }}
  secretObjects:
  - secretName: {{ include "myk8schart.secretProviderName" . }}
    type: Opaque
    labels:
      app: {{ include "myk8schart.secretProviderName" . }}
    data:
      {{- range .Values.azureKeyVault.secrets }}
      - key: {{ .alias }}
        objectName: {{ .alias }}
      {{- end }}
{{- end }}