{{- if .Values.enabledTlsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secret
type: kubernetes.io/tls
data:
    tls.crt: |-
      {{ .Files.Get (printf "%s%s" .Values.tlsSecret.fileName ".crt") | b64enc | indent 4 }}
    tls.key: |-
      {{ .Files.Get (printf "%s%s" .Values.tlsSecret.fileName ".key") | b64enc | indent 4 }}
{{- end }}