apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalName }}
  ports:
    - name: sql
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}